SELECT DISTINCT CC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CC
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH ON CC.CAR_ID = CH.CAR_ID
WHERE CC.CAR_TYPE = '세단' AND CH.START_DATE LIKE '2022-10%'
ORDER BY CC.CAR_ID DESC 
