SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.ITEM_ID 
WHERE IT.PARENT_ITEM_ID IN (
                            SELECT TEMP_II.ITEM_ID
                            FROM ITEM_INFO TEMP_II
                            LEFT JOIN ITEM_TREE TEMP_IT ON TEMP_II.ITEM_ID = TEMP_IT.ITEM_ID 
                            WHERE TEMP_II.RARITY='RARE'
)
ORDER BY II.ITEM_ID DESC


# 0 A R 10000 NULL
# 1 B R 9000  0
# 2 C L 11000 0
# 3 D R 10000 1
# 4 E R 12000 1
