SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (COPY.SIZE-ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM ECOLI_DATA ED
LEFT JOIN ( SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
            FROM ECOLI_DATA
            GROUP BY YEAR(DIFFERENTIATION_DATE)
          ) AS COPY
ON YEAR(ED.DIFFERENTIATION_DATE)= (COPY.YEAR)
ORDER BY YEAR ASC, YEAR_DEV ASC;

