SELECT CC.CAR_ID, ROUND(AVG(DATEDIFF(CC.END_DATE,CC.START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CC
GROUP BY CAR_ID
HAVING AVERAGE_DURATION>=7
ORDER BY AVERAGE_DURATION DESC, CC.CAR_ID DESC
