SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, SKILLCODES
WHERE (DEVELOPERS.SKILL_CODE & SKILLCODES.CODE)=SKILLCODES.CODE AND (SKILLCODES.NAME ='C#' OR SKILLCODES.NAME ='Python')
ORDER BY ID
