SELECT AI.ANIMAL_ID, AI.NAME, 
    CASE WHEN AI.SEX_UPON_INTAKE LIKE '%Neutered%' THEN 'O'
         WHEN AI.SEX_UPON_INTAKE LIKE '%Spayed%' THEN 'O'
         ELSE 'X'
    END AS 중성화
FROM ANIMAL_INS AI

