# #방법 1
# SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
# FROM REST_INFO, REST_REVIEW 
# WHERE REST_INFO.REST_ID = REST_REVIEW.REST_ID AND ADDRESS LIKE '서울%'
# GROUP BY(REST_INFO.REST_ID)
# ORDER BY SCORE DESC, FAVORITES DESC


# 방법 2 : LEFT JOIN을 썼으므로, REVIEW IS NOT NULL 반드시 써야함!
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO
LEFT JOIN REST_REVIEW ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE ADDRESS LIKE '서울%' AND REVIEW_SCORE IS NOT NULL
GROUP BY REST_INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;


