SELECT CH.HISTORY_ID, 
ROUND(CC.DAILY_FEE*(DATEDIFF(CH.END_DATE,CH.START_DATE)+1)
      * CASE
            WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 >=90 THEN (SELECT (1-DISCOUNT_RATE/100) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE='트럭' AND CAR_RENTAL_COMPANY_DISCOUNT_PLAN.DURATION_TYPE='90일 이상')
            WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 >=30 THEN (SELECT (1-DISCOUNT_RATE/100) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE='트럭' AND CAR_RENTAL_COMPANY_DISCOUNT_PLAN.DURATION_TYPE='30일 이상')
             WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 >=7 THEN (SELECT (1-DISCOUNT_RATE/100) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE='트럭' AND CAR_RENTAL_COMPANY_DISCOUNT_PLAN.DURATION_TYPE='7일 이상')
         ELSE 1
         END
     ,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC, CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
WHERE CC.CAR_ID = CH.CAR_ID AND CC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CH.HISTORY_ID DESC;
